print("## Program Python Biodata Mahasiswa ##")
print("==================================================")

nama = input('Nama mahasiswa: ')
nim = int(input('NIM: '))
fakultas = input('Fakultas: ')
jurusan = input('Jurusan: ')
kota_asal = input('Kota Asal: ')
alamat = input('Alamat: ')

print()
print('# Data Mahasiswa #')
print('==================')
print('Nama:',nama)
print('NIM:',nim)
print('Fakultas:',fakultas)
print('Jurusan:',jurusan)
print('Kota Asal:',kota_asal)
print('Alamat:',alamat)

